"""empty message

Revision ID: 33848c6e1089
Revises: b1386d24e8f0
Create Date: 2024-09-03 12:47:12.685024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '33848c6e1089'
down_revision: Union[str, None] = 'b1386d24e8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_parametrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mh_id', sa.Uuid(), nullable=False))
        batch_op.alter_column('temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_constraint('patient_parametrics_patient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'medical_history', ['mh_id'], ['id'])
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_parametrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('patient_parametrics_patient_id_fkey', 'patient', ['patient_id'], ['id'])
        batch_op.alter_column('temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('mh_id')

    # ### end Alembic commands ###
