"""empty message

Revision ID: 99ef5b6dd64c
Revises: bf49e4037521
Create Date: 2024-08-05 16:06:46.177370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '99ef5b6dd64c'
down_revision: Union[str, None] = 'bf49e4037521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lotus_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_department_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('income_date', sa.DateTime(), nullable=True),
    sa.Column('outcome_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lotus_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_history')
    # ### end Alembic commands ###
