"""empty message

Revision ID: b1386d24e8f0
Revises: 99ef5b6dd64c
Create Date: 2024-09-03 12:23:00.859709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b1386d24e8f0'
down_revision: Union[str, None] = '99ef5b6dd64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_parametrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('check_datetime', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('upper_ad', sa.Integer(), nullable=True),
    sa.Column('lower_ad', sa.Integer(), nullable=True),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('oxygen', sa.Integer(), nullable=True),
    sa.Column('drinked', sa.Integer(), nullable=True),
    sa.Column('infuzi', sa.Integer(), nullable=True),
    sa.Column('diurez', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('imt', sa.Float(), nullable=True),
    sa.Column('stool', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_parametrics')
    # ### end Alembic commands ###
