"""empty message

Revision ID: bf49e4037521
Revises: f35095320abd
Create Date: 2024-08-02 15:16:43.867127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bf49e4037521'
down_revision: Union[str, None] = 'f35095320abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('main_issue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mkb', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ksg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('standart', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diagnosis_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_type_id'], ['diagnosis_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lotus_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_department_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('income_date', sa.Date(), nullable=True),
    sa.Column('outcome_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_history')
    op.drop_table('diagnosis')
    op.drop_table('diagnosis_type')
    # ### end Alembic commands ###
